### ISSUE TITLE
Worried about your wellbeing

### ISSUE THREAD

**Issue by internetztube** [wongmjane/typescout#252]
Hello!
Today I noticed a thread on Twitter where some people are very concerned about you. Would be great if you could maybe give us a sign that you're okay. 
https://twitter.com/cherthedev/status/1422190940836438021/

**Comment by huuphongnguyen** [comment]
I did not think one day we would find a way to contact Jane like this. 🥺
Hope you being well Jane. What ever happened, for me you are still a great girl and I always follow your things. *AirHug.

**Comment by internetztube** [comment]
![Screenshot 2021-08-03 at 14 09 55](https://user-images.githubusercontent.com/6382364/128012961-796eea99-093c-4b1b-9ba9-3aad67d41d12.png)
https://twitter.com/trynothingy/status/1422527318707167238
